### PR TITLE
Add `aws-role-duration-seconds` input for configuring aws credentials

### PR DESCRIPTION
**Pull request by anGie44**
Closes https://github.com/hashicorp/ghaction-terraform-provider-release/issues/2

### CODE REVIEW

**Comment by anGie44** [comment]
Thanks for the speedy review @bflad !

**Comment by anGie44** [comment]
Ahh i didn't update the README 🤦‍♀️ .. will add that in another commit

**Review by bflad — APPROVED** [review]
Looks great, let's do it! 🚀

**Comment by bflad** [comment]
The `v1` tag has been updated with this change.

**Pull request merged**
